services:
  scylla-front:
    image: ${PRELUDE_FRONTEND_IMAGE_NAME:-godlyjaaaaj/scylla-prelude}:${APP_VERSION:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    container_name: scylla-prelude-frontend
    restart: unless-stopped
    volumes:
      - surrealdb_data:/app/data
    networks:
      - reverse_proxy_scylla-network

volumes:
  surrealdb_data:

networks:
  reverse_proxy_scylla-network:
    external: true
