services:
  scylla-front:
    image: ${PRELUDE_FRONTEND_IMAGE_NAME:-godlyjaaaaj/scylla-prelude}:${APP_VERSION:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: scylla-prelude-frontend
    restart: unless-stopped
    ports:
      - "${PRELUDE_FRONTEND_PORT:-8080}:80"
    networks:
      - scylla-network

networks:
  scylla-network:
    external: true