server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/snippets/security_headers.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pour les assets statiques
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";

        include /etc/nginx/snippets/security_headers.conf;
    }

    # Erreurs
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}